### ISSUE TITLE
States never updating

### ISSUE THREAD

**Issue by Techbot121** [Metastruct/gmod_discordrpc#4]
this makes this basically useless, it just fires the activity once, but I assume this is still being worked on.

**Comment by Tenrys** [comment]
yes, you're supposed to implement the hooks / events that update the activity yourself

**Comment by Tenrys** [comment]
nevermind i get what you mean

**Comment by Tenrys** [comment]
all this needs is a timer really

**Comment by Techbot121** [comment]
nah just let the state decide how to do it.

**Comment by Tenrys** [comment]
well nothing stops you from adding hooks / timers and running discordrpc.SetActivity with state shit, that's what I mean
